### ISSUE TITLE
Treat transparency like black

### ISSUE THREAD

**Issue by FOSSBOSS** [FineFindus/artem#10]
Treat transparency like black

**Describe the solution you'd like**
Treat transparency like black
Program is neat, works great,but it would be helpful if transparent image sections were converted to blank spaces the same way black spaces are.

**Describe alternatives you've considered**
Edit the code myself (really busy rn, 14 hr nights 30 day shut down cant take more projects right now)
Maybe caca or toilet can do it.
manually editing the file, it would be boring, but I could do it.
manually editing the images also boring, also doable. 

**Additional context**
Doing A cli animated ascii art thing. I used to do this all the time like 12 years ago, in college, but I forgot how. 

**Information**
OS Ubuntu 20.04
Shell Bash
- OS: [e.g. Ubuntu 20.10]
- Shell: Bash
- Version: 5.0.17(1)-release

**Comment by FineFindus** [comment]
Could you please provide an example image where this happens? I can't reproduce it, the transparent spaces on my test images are converted to blank spaces.

**Comment by FOSSBOSS** [comment]
heres an image with transparent background which is converted to text
And here is its conversion

I also just realized where the question was version, it didnt mean my bash shell.
I'm using the latest deb package
![f57](https://user-images.githubusercontent.com/1
![trans](https://user-images.githubusercontent.com/12141764/191057994-09a8de01-d833-4e41-9251-73f028fafd19.png)
2141764/191057507-f5e4c2b8-cd7b-40b9-a411-03df4129b661.png)

**Comment by FOSSBOSS** [comment]
![f57](https://user-images.githubusercontent.com/12141764/191058457-aef62e53-58d5-4490-8d0d-cdb197c5d836.png)

image with transparent bg

**Comment by FineFindus** [comment]
This is actually intended behavior. The background is not completely transparent, instead is has a few colored pixels:
![image](https://user-images.githubusercontent.com/63370021/191063126-49976bf9-c331-44f7-a18b-e29ef5d4536d.png)

If you want a completely transparent background, you will need to edit and remove the colored pixels in another program beforehand, image editing is not in the scope of `artem`.
