### ISSUE TITLE
output html: make pre end tag below text body

### ISSUE THREAD

**Issue by FOSSBOSS** [FineFindus/artem#11]
**Is your feature request related to a problem? Please describe.**
It would be nice if the pre tag close was below the last line of text
making the text body its own block

**Describe the solution you'd like**
this: "</pre></body></html>" to be on a line below the last line of the text body. Or:
this: "</pre></body></html>" like this:
"</pre>"
"</body></html>"
**Describe alternatives you've considered**
learn enough rust to edit this code. 

**Additional context**
I'm going to use this to make animated ascii art frames in the animation where the </pre></body></html>
tags are makes that less easy

**Information**

- OS: [e.g. Ubuntu 20.04
- Shell: Bash
- Version: 5.0.17(1)-release

**Comment by FineFindus** [comment]
I added a line break before the `</pre>`tag.

This will probably not be a new release for a while (waiting for a few more things to be included), so I would recommend compiling the master branch yourself (it should be stable) if you need this immediately.
