### ISSUE TITLE
docs: Change ans to ansi

### ISSUE THREAD

**Issue by undeadbydawn** [FineFindus/artem#17]
Instructions contain two typos in the following lines:

```
# or alternatively, use an .asn file for colored ascii text
artem PATH --output ascii.ans
```
filetype should be .ansi or the resulting art is mono

**Comment by FineFindus** [comment]
This is not a typo, `artem` accepts both `.ansi` and `.ans` files for coloured text output. Also, I couldn't find any source saying that only `ansi` files can contain coloured text, please cite sources.

**Comment by FineFindus** [comment]
In which editor did you open it? This is probably just an editor issue, e.g. when using an [VS Code extension](https://marketplace.visualstudio.com/items?itemName=Tobias-Faller.vt100-syntax-highlighting) both files are colored.
