### ISSUE TITLE
Install fail on Garuda Dr460nized (arch)

### ISSUE THREAD

**Issue by undeadbydawn** [FineFindus/artem#6]
**Describe the bug**
Tried to install via paru, failed with

`install: cannot stat 'completions/_artem': No such file or directory`

(issue also raised on Reddit, posted here for official purposes)

**Information**

- OS: Garuda Dr460nized, kernel 5.18.0-258-tkg-cfs
- Shell: zsh
- Version: ?

**Comment by FineFindus** [comment]
That should definitely not happen.
Did you try to install the binary (`artem-bin`) or the complied (`artem`) version?

**Comment by FineFindus** [comment]
I found the bug and fixed (it was simply the  wrong path). Thanks for submitting the bug, it should now all be correctly install.
